In [35]:
###########################
# Pre-processing the data #
###########################


import pandas as pd
import numpy as np

files = ['miller_idle', 'sam_wild', 'layton_idle', 'miller_wild', 'val_idle', 'layton_wild', 'sam_idle', 'val_wild']  #filename in the folder 

In [36]:
num_attributes = 6
num_targets = 3

data = np.empty((0,num_attributes)) #initializing empty array with proper shape
targets = np.empty((0,num_targets)) #empty array for targets

#collecting all the data into one set
for f in files:
    processed_data, processed_targets = preprocessing(f)
    data = np.append(data, processed_data, axis=0)
    targets = np.append(targets, processed_targets, axis=0)
    save_array(processed_data, f)

In [37]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, targets, test_size=0.33)


from sklearn.model_selection import GridSearchCV
parameters = {
    'alpha':(0.1, 0.3, 1.0, 3.0, 10.0), 
    'solver': ('auto') # alternatives: 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga'
} #hyperparameters to search through with CV


#searching through all combinations of parameters to find best (ranked by CV)
reg = GridSearchCV(Ridge(), parameters) 
reg.fit(X_train, y_train)  

#scoring against test set to see how good our model is
print(reg.score(X_test, y_test))

0.983087920767


In [38]:
print('data:')
print(X_test[:10, 2:5])
print('\npredictions:')
print(reg.predict(X_test)[:10])
print('\ntargets:')
print(y_test[:10])

data:
[[-0.093   0.5039 -0.89  ]
 [ 0.0585  0.6757 -0.753 ]
 [ 0.4257 -0.089   0.8671]
 [-0.054  -0.519   0.7109]
 [-0.316   0.2421 -0.949 ]
 [-0.007  -0.527   0.7578]
 [ 0.9648  0.2343 -0.105 ]
 [ 0.2734 -0.429   0.7539]
 [ 0.7421  0.2812 -0.57  ]
 [ 0.2695 -0.359   0.8046]]

predictions:
[[-0.08558059  0.49781231 -0.89078858]
 [ 0.06608185  0.66181912 -0.7571996 ]
 [ 0.42787564 -0.09941802  0.86002548]
 [-0.04920978 -0.51181435  0.70752002]
 [-0.31100801  0.24554172 -0.94704633]
 [-0.00622175 -0.52207282  0.75635613]
 [ 0.9613154   0.23143152 -0.10426771]
 [ 0.2735992  -0.42483608  0.75111651]
 [ 0.73470322  0.27756839 -0.55952956]
 [ 0.27393895 -0.35854889  0.80151536]]

targets:
[[-0.089   0.5078 -0.875 ]
 [ 0.0546  0.6992 -0.761 ]
 [ 0.4453 -0.042   0.8359]
 [-0.05   -0.593   0.7148]
 [-0.316   0.246  -0.949 ]
 [ 0.0039 -0.539   0.75  ]
 [ 0.9687 -0.007  -0.07  ]
 [ 0.2343 -0.46    0.7851]
 [ 0.7343  0.3164 -0.605 ]
 [ 0.1835 -0.257   0.8515]]
